name: second
  
on: push

jobs:
  job1:
    name: Ubuntu date
    runs-on: ubuntu-latest
    steps:
      - name: 1-checkout
        uses: actions/checkout@v2
      - name: 2-getdate
        run: date '+%F %T'
  job2:
    name: Windows date
    runs-on: windows-latest
    steps:
      - name: 1-checkout
        uses: actions/checkout@v2
      - name: 2-getdate
        run: Get-Date -format 'yyyy-MM-dd HH:mm:ss'
  job3:
    name: MacOS date
    runs-on: macos-latest
    steps:
      - name: 1-checkout
        uses: actions/checkout@v2
      - name: 2-getdate
        run: date '+%F %T'     
  job4:
    name: Python date
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    needs: [job1, job2, job3]
    steps:
      - name: 1-checkout
        uses: actions/checkout@v2
      - name: 2-Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 3-Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 4
        run: python3 python_date.py